/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// https://developers.e.qq.com/docs/api/business_assets/video/videos_add

package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"

	"github.com/tencentad/marketing-api-go-sdk/pkg/ads"
	"github.com/tencentad/marketing-api-go-sdk/pkg/api"
	"github.com/tencentad/marketing-api-go-sdk/pkg/config"
	"github.com/tencentad/marketing-api-go-sdk/pkg/errors"
	"github.com/tencentad/marketing-api-go-sdk/pkg/model"
)

type VideosAddExample struct {
	TAds          *ads.SDKClient
	AccessToken   string
	AccountId     int64    `json:"account_id"` // 推广帐号 id，有操作权限的帐号 id，包括代理商和广告主帐号 id
	VideoFile     *os.File `json:"video_file"` // 被上传的视频文件，视频二进制流，支持上传的视频文件类型为：mp4、mov、avi, 最大支持 100M 视频上传
	Signature     string   `json:"signature"`  // 视频文件签名  字段长度为 32 字节
	VideosAddOpts *api.VideosAddOpts
}

func (e *VideosAddExample) Init() {
	e.AccessToken = "YOUR ACCESS TOKEN"
	e.TAds = ads.Init(&config.SDKConfig{
		AccessToken: e.AccessToken,
		IsDebug:     true,
	})
	e.AccountId = int64(0)
	file, err := os.Open("YOUR FILE PATH")
	if err != nil {
		e.VideoFile = file
	}
	e.Signature = "signature_example"
	e.VideosAddOpts = &api.VideosAddOpts{}
}

func (e *VideosAddExample) RunExample() (model.VideosAddResponseData, http.Header, error) {
	tads := e.TAds
	// change ctx as needed
	ctx := *tads.Ctx
	return tads.Videos().Add(ctx, e.AccountId, e.VideoFile, e.Signature, e.VideosAddOpts)
}

func main() {
	e := &VideosAddExample{}
	e.Init()
	response, headers, err := e.RunExample()
	if err != nil {
		if resErr, ok := err.(errors.ResponseError); ok {
			errStr, _ := json.Marshal(resErr)
			fmt.Println("Response error:", string(errStr))
		} else {
			fmt.Println("Error:", err)
		}
	}
	fmt.Println("Response data:", response)
	fmt.Println("Headers:", headers)
}
