/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// https://developers.e.qq.com/docs/sdk/business_assets/image/images_add

package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/antihax/optional"
	"github.com/tencentad/marketing-api-go-sdk/pkg/ads"
	"github.com/tencentad/marketing-api-go-sdk/pkg/api"
	"github.com/tencentad/marketing-api-go-sdk/pkg/config"
	"github.com/tencentad/marketing-api-go-sdk/pkg/errors"
	"github.com/tencentad/marketing-api-go-sdk/pkg/model"
)

type ImagesAddExample struct {
	TAds          *ads.SDKClient
	AccessToken   string
	AccountId     int64  `json:"account_id"`  // 推广帐号 id，有操作权限的帐号 id，包括代理商和广告主帐号 id
	UploadType    string `json:"upload_type"` // 上传方式，[枚举详情](https://developers.e.qq.com/docs/reference/enum#api_image_upload_type) 枚举列表：{ UPLOAD_TYPE_FILE, UPLOAD_TYPE_BYTES }
	Signature     string `json:"signature"`   // 图片文件签名，使用图片文件的 md5 值，用于检查上传图片文件的完整性 字段长度为 32 字节
	ImagesAddOpts *api.ImagesAddOpts
}

func (e *ImagesAddExample) Init() {
	e.AccessToken = "YOUR ACCESS TOKEN"
	e.TAds = ads.Init(&config.SDKConfig{
		AccessToken: e.AccessToken,
		IsDebug:     true,
	})
	e.AccountId = int64(0)
	e.UploadType = "UPLOAD_TYPE_FILE"
	e.Signature = "signature_example"
	e.ImagesAddOpts = &api.ImagesAddOpts{

		File: optional.NewInterface("YOUR IMAGE FILE PATH"),
	}
}

func (e *ImagesAddExample) RunExample() (model.ImagesAddResponseData, http.Header, error) {
	tads := e.TAds
	// change ctx as needed
	ctx := *tads.Ctx
	return tads.Images().Add(ctx, e.AccountId, e.UploadType, e.Signature, e.ImagesAddOpts)
}

func main() {
	e := &ImagesAddExample{}
	e.Init()
	response, headers, err := e.RunExample()
	if err != nil {
		if resErr, ok := err.(errors.ResponseError); ok {
			errStr, _ := json.Marshal(resErr)
			fmt.Println("Response error:", string(errStr))
		} else {
			fmt.Println("Error:", err)
		}
	}
	fmt.Println("Response data:", response)
	fmt.Println("Headers:", headers)
}
