/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/tencentad/marketing-api-go-sdk/pkg/ads"
	"github.com/tencentad/marketing-api-go-sdk/pkg/config"
	"github.com/tencentad/marketing-api-go-sdk/pkg/errors"
	"github.com/tencentad/marketing-api-go-sdk/pkg/model"
)

type AssetPermissionsAddExample struct {
	TAds        *ads.SDKClient
	AccessToken string
	Data        model.AssetPermissionsAddRequest
}

func (e *AssetPermissionsAddExample) Init() {
	e.AccessToken = "YOUR ACCESS TOKEN"
	e.TAds = ads.Init(&config.SDKConfig{
		AccessToken: e.AccessToken,
		IsDebug:     true,
	})
	var accountId int64 = 0
	var assetId int64 = 0
	e.Data = model.AssetPermissionsAddRequest{
		LicensingAccountIdList: &[]int64{int64(0)},
		AccountId:              &accountId,
		AssetType:              model.AssetType_CANVAS_WECHAT,
		AssetPermissionSpec: &[]model.AssetPermissionSpecStruct{{
			AssetPermissionGrantType: model.AssetPermissionGrantType_ASSET,
			AssetId:                  &assetId,
		}},
	}
}

func (e *AssetPermissionsAddExample) RunExample() (model.AssetPermissionsAddResponseData, http.Header, error) {
	tads := e.TAds
	// change ctx as needed
	ctx := *tads.Ctx
	return tads.AssetPermissions().Add(ctx, e.Data)
}

func main() {
	e := &AssetPermissionsAddExample{}
	e.Init()
	response, headers, err := e.RunExample()
	if err != nil {
		if resErr, ok := err.(errors.ResponseError); ok {
			errStr, _ := json.Marshal(resErr)
			fmt.Println("Response error:", string(errStr))
		} else {
			fmt.Println("Error:", err)
		}
	}
	fmt.Println("Response data:", response)
	fmt.Println("Headers:", headers)
}
