package bean

var EducationStatusesMap = map[int]string{
	1:  "HIGH_SCHOOL",
	2:  "UNDERGRAD",
	3:  "ALUM",
	4:  "HIGH_SCHOOL_GRAD",
	5:  "SOME_COLLEGE",
	6:  "ASSOCIATE_DEGREE",
	7:  "IN_GRAD_SCHOOL",
	8:  "SOME_GRAD_SCHOOL",
	9:  "MASTER_DEGREE",
	10: "PROFESSIONAL_DEGREE",
	11: "DOCTORATE_DEGREE",
	12: "UNSPECIFIED",
	13: "SOME_HIGH_SCHOOL",
}
